const C = {
  ADD_TODO: "ADD_TODO",
  REMOVE_TODO: "REMOVE_TODO",
  CHECK_TODO: "CHECK_TODO",
  UNCHECK_TODO: "UNCHECK_TODO",
  SHOW_COMPLETED: "SHOW_COMPLETED",
  HIDE_COMPLETED: "HIDE_COMPLETED",
  CLEAR_TODOINPUT: "CLEAR_TODOINPUT",
  SET_TODOINPUT: "SET_TODOINPUT",
  SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',
}


export default C